DROP TABLE IF EXISTS note;

CREATE TABLE IF NOT EXISTS note
(
    id   UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    title VARCHAR(200) NOT NULL CHECK (length(title) > 1),
    content VARCHAR(2000) NOT NULL CHECK (length(title) > 1)
);